name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag nagygao/github-test:test
          docker image ls
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker push nagygao/github-test:test
      - name: Terraform apply
        working-directory: terraform
        env:
          TF_VAR_kube_config: ${{ secrets.KUBE_CONFIG}}
        run: |
          echo ${{ github.TOKEN }}
          terraform init
          terraform apply -auto-approve
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 120
        with:
          secret: ${{ github.TOKEN }}
          approvers: nagygao
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
      - name: Terraform destroy
        working-directory: terraform
        env:
          TF_VAR_kube_config: ${{ secrets.KUBE_CONFIG}}
        run: |
          sleep 30
          terraform destroy -auto-approve
