name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag nagygao/github-test:test
          docker image ls
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker push nagygao/github-test:test
      - name: Terraform apply
        env:
          kube_config: ${{ secrets.KUBE_CONFIG}}
        run: |
          export TF_VAR_kube_config=kube_config
          cd terraform
          terraform init
          terraform apply -auto-approve
          sleep 30
          terraform destroy -auto-approve
