on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Hello world action step
        run: |
          echo Hello World!
          docker build -t actions-test:latest .
